version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
    - ryanfowler
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - ryanfowler
