name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.20' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      run: make install
    - name: Lint
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1"
        install-go: false
        cache-key: ${{ matrix.go }}
    - name: Test
      run: make test
